# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see README (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: CI

on: # this determines when this workflow is run
  # push:
  #    branches: [ main ] #  when branch is pushed to
  pull_request:
     branches: [ master ] # when there is a pull request against branch
  workflow_dispatch: # allow manually starting this workflow

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    runs-on: ubuntu-22.04
    strategy:
      matrix: # matrix is the product of entries
        ROS_DISTRO: [humble]
        ROS_REPO: [main]
    env:
      AFTER_INIT: "apt-get -qq install -y --no-upgrade --no-install-recommends libboost-all-dev libyaml-cpp-dev"
    steps:
      - name: checkout current repo
        uses: actions/checkout@v3 # clone target repository
        with:
          path: "./hesai_ros_driver"
      
      - uses: 'ros-industrial/industrial_ci@master' # run industrial_ci
        env: # either pass all entries explicitly
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.ROS_REPO }}
        # with: # or pass the full matrix as config
        #    config: ${{toJSON(matrix)}}

